<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Title>LibreTranslatePlugin</Title>
    <Authors>silverx69</Authors>
    <Company>Cloud3d Games</Company>
    <Copyright>silverx69 © 2023</Copyright>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/silverx69/AthenaBot.git</RepositoryUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AthenaBot.Core\AthenaBot.Core.csproj" />
  </ItemGroup>
  <!-- 
  When debugging .exe it will load plugins from data folder
  These build events will copy Plugin/Dependencies to data folder automatically.
  Commands assume plugins are to be placed in "AppData\Roaming\AthenaBot" on Windows, modify as necessary for other targets.
  -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;%25APPDATA%25\AthenaBot\Plugins\$(TargetName)\&quot;&#xD;&#xA;copy &quot;$(TargetDir)*&quot; &quot;%25APPDATA%25\AthenaBot\Plugins\$(TargetName)\*&quot;" />
  </Target>
</Project>